#!/bin/bash
#trim space
#read  -rd '' tabs <<< "$tabs"

module=$1
shift

arg=$#
if [ ! $arg -gt 0 ];then
 bin=$(basename $0)
 echo "Usage: $bin <module> <table...>"
 exit 0
fi

function generate {
   module=$1
   table=$2   
   mvn com.jfeat:sb-code-generator:1.2.0:generate -DmoduleName=$module -Dtable=$table -f code-generator-pom.xml
}

for item in "$@"; do
  #process each table
  generate $module $item
done

